# Generated by Django 5.0.6 on 2024-05-11 16:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sex', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('region', models.CharField(max_length=255)),
                ('sub_city', models.CharField(max_length=255)),
                ('woreda', models.CharField(max_length=255)),
                ('home_no', models.CharField(max_length=255)),
                ('birth_place', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('occupation', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=255)),
                ('warrantor', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('non_fixed', 'Non-Fixed'), ('storeman', 'Storeman'), ('mmd', 'Mmd'), ('otherdir', 'Otherdir')], max_length=20),
        ),
        migrations.AddField(
            model_name='personalinfotable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
