# Generated by Django 5.0.6 on 2024-05-13 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_personalinfotable_delete_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfotable',
            name='id',
        ),
        migrations.AlterField(
            model_name='personalinfotable',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
