# Generated by Django 5.0.6 on 2024-05-11 16:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('ca_id', models.AutoField(primary_key=True, serialize=False)),
                ('ca_name', models.CharField(max_length=255)),
                ('ca_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('delivery_name', models.CharField(max_length=100)),
                ('delivery_id', models.CharField(max_length=50, unique=True)),
                ('company_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('schedule_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Distributed', 'Distributed'), ('NotDistributed', 'Not Distributed')], max_length=50)),
                ('allocator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocated_allocations', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_allocations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributed_date', models.DateField(default=django.utils.timezone.now)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='store.allocation')),
                ('storeman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('InProgress', 'In Progress')], default='InProgress', max_length=50)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='allocation',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='store.order'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=255)),
                ('import_means', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('serial_no', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Allocated', 'Allocated'), ('Distributed', 'Distributed'), ('Free', 'Free')], default='Free', max_length=50)),
                ('inserted_date', models.DateField(default=django.utils.timezone.now)),
                ('t_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('u_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reciever', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.product'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='store.product'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='store.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='suppleir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.supplier'),
        ),
    ]
